// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/forgot-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Request password reset for a registered user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Forgot password",
                "parameters": [
                    {
                        "description": "User email for password reset",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/__.ResetPasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.Empty"
                        }
                    },
                    "400": {
                        "description": "Error while requesting password reset",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Log in a registered user with username and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Log in user",
                "parameters": [
                    {
                        "description": "User login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/__.LogInReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.LogInResp"
                        }
                    },
                    "400": {
                        "description": "Error while logging in",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error while logging in",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/refreshTokenRequest": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Refresh access token using refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Refresh token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.RefreshTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Error while refreshing the token",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Register a new user with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/__.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.RegisterResp"
                        }
                    },
                    "400": {
                        "description": "Error while registering",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error while registering",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/reset-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Request password reset for a registered user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Reset password",
                "parameters": [
                    {
                        "description": "User email for password reset",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/__.ResetPasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.Empty"
                        }
                    },
                    "400": {
                        "description": "Error while requesting password reset",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error while requesting password reset",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/learning/add_word": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add a new word to the vocabulary for the current language",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Learning"
                ],
                "summary": "Add a new word",
                "parameters": [
                    {
                        "description": "New word details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/__.AddNewWordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.AddNewWordResp"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/learning/all_languages": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a list of all languages available for learning",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Learning"
                ],
                "summary": "Get all available languages",
                "responses": {
                    "200": {
                        "description": "List of languages",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/__.GetAllLanguagesResp"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/learning/complete_lesson/{id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Complete the current lesson and update progress",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Learning"
                ],
                "summary": "Complete a lesson",
                "parameters": [
                    {
                        "description": "Lesson completion details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/__.CompleteLessonReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.CompleteLessonResp"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/learning/list_vocabulary/{language_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a list of all vocabulary for the current language",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Learning"
                ],
                "summary": "Get all vocabulary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Language ID",
                        "name": "language_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of vocabulary",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/__.Vocabulary"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/learning/participate_lesson/{lesson_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Participate in an ongoing lesson and retrieve lesson details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Learning"
                ],
                "summary": "Participate in a lesson",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lesson ID",
                        "name": "lesson_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.ParticipateLessonResp"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/learning/start_exercise/{exercise_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Start a new exercise for the current lesson",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Learning"
                ],
                "summary": "Start a new exercise",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Exercise ID",
                        "name": "exercise_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.StartExerciceResp"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/learning/start_lesson": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Start a new lesson for the selected language",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Learning"
                ],
                "summary": "Start a new lesson",
                "parameters": [
                    {
                        "description": "Lesson start details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/__.StartLearningReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.StartLearningResp"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/learning/submit_answer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submit an answer for the current exercise",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Learning"
                ],
                "summary": "Submit an answer for an exercise",
                "parameters": [
                    {
                        "description": "Answer submission details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/__.AnswerExerciseReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.AnswerExerciseResp"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/progress/achievements/{user_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve the achievements of a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Progress"
                ],
                "summary": "Get user achievements",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.AchievementsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/progress/by_language/{language_id}/{user_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve the progress of a user for a specific language and user ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Progress"
                ],
                "summary": "Get user progress by language and user ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Language ID",
                        "name": "language_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.ProgressByLanguageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/progress/daily/{user_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve the daily progress of a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Progress"
                ],
                "summary": "Get daily progress",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.DailyProgressResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/progress/leader/{user_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve the leaderboard for a specific language",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Progress"
                ],
                "summary": "Get leaderboard by language",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Language ID",
                        "name": "language_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.LeaderboardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/progress/monthly/{user_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve the monthly progress of a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Progress"
                ],
                "summary": "Get monthly progress",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.MonthlyProgressResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/progress/skills/{language_id}/{user_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve the skills of a user for a specific language",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Progress"
                ],
                "summary": "Get user skills by language",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Language ID",
                        "name": "language_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.SkillsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/progress/weekly/{user_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve the weekly progress of a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Progress"
                ],
                "summary": "Get weekly progress",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.WeeklyProgressResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/change-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Change password for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Change user password",
                "parameters": [
                    {
                        "description": "User password change details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/__.ChangePasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.Empty"
                        }
                    },
                    "400": {
                        "description": "Error while changing the password",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error while changing the password",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/profile": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update profile information for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user profile",
                "parameters": [
                    {
                        "description": "Updated user profile details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/__.UpdateProfileReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.UpdateProfileResp"
                        }
                    },
                    "400": {
                        "description": "Error while updating profile",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error while updating profile",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/profile/{user_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get profile information for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user profile information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.GetProfileInfoResp"
                        }
                    },
                    "400": {
                        "description": "Error while getting profile info",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error while getting profile info",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/settings": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update settings for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user settings",
                "parameters": [
                    {
                        "description": "Updated user settings details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/__.UpdateSettingsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.Empty"
                        }
                    },
                    "400": {
                        "description": "Error while updating settings",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error while updating settings",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/settings/{user_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get settings for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user settings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/__.GetUserSettingsResp"
                        }
                    },
                    "400": {
                        "description": "Error while getting user's settings",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error while getting user's settings",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "__.Achievement": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "earned_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "__.AchievementsResponse": {
            "type": "object",
            "properties": {
                "achievements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/__.Achievement"
                    }
                }
            }
        },
        "__.AddNewWordReq": {
            "type": "object",
            "properties": {
                "vocabulary": {
                    "$ref": "#/definitions/__.Vocabulary"
                }
            }
        },
        "__.AddNewWordResp": {
            "type": "object",
            "properties": {
                "language_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "word_id": {
                    "type": "string"
                }
            }
        },
        "__.AnswerExerciseReq": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "exercise_id": {
                    "type": "string"
                }
            }
        },
        "__.AnswerExerciseResp": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "earned_exp": {
                    "type": "integer"
                },
                "isCorrect": {
                    "type": "boolean"
                }
            }
        },
        "__.ChangePasswordReq": {
            "type": "object",
            "properties": {
                "current_password": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "__.CompleteLessonReq": {
            "type": "object",
            "properties": {
                "lesson_id": {
                    "type": "string"
                }
            }
        },
        "__.CompleteLessonResp": {
            "type": "object",
            "properties": {
                "exp_earned": {
                    "type": "integer"
                },
                "next_lesson": {
                    "$ref": "#/definitions/__.Lessons"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "__.DailyProgressResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "lessons_completed": {
                    "type": "integer"
                },
                "minutes_practiced": {
                    "type": "integer"
                },
                "new_words_learned": {
                    "type": "integer"
                },
                "streak_days": {
                    "type": "integer"
                },
                "xp_earned": {
                    "type": "integer"
                }
            }
        },
        "__.Empty": {
            "type": "object",
            "properties": {
                "isTrue": {
                    "type": "boolean"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "__.Exercise": {
            "type": "object",
            "properties": {
                "correct_answer": {
                    "type": "string"
                },
                "exercise_id": {
                    "type": "string"
                },
                "questions": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "__.GetAllLanguagesResp": {
            "type": "object",
            "properties": {
                "languages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/__.Languages"
                    }
                }
            }
        },
        "__.GetProfileInfoResp": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "learning_languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "native_language": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "__.GetUserSettingsResp": {
            "type": "object",
            "properties": {
                "daily_goal": {
                    "type": "string"
                },
                "difficulty_level": {
                    "type": "string"
                },
                "notifications_enabled": {
                    "type": "boolean"
                },
                "preferred_learning_time": {
                    "type": "string"
                }
            }
        },
        "__.Languages": {
            "type": "object",
            "properties": {
                "flag_emoji": {
                    "type": "string"
                },
                "language_code": {
                    "type": "string"
                },
                "language_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "__.LeaderboardEntry": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                },
                "xp": {
                    "type": "integer"
                }
            }
        },
        "__.LeaderboardResponse": {
            "type": "object",
            "properties": {
                "language": {
                    "type": "string"
                },
                "leaderboard": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/__.LeaderboardEntry"
                    }
                },
                "user_rank": {
                    "type": "integer"
                }
            }
        },
        "__.Lessons": {
            "type": "object",
            "properties": {
                "completed": {
                    "type": "boolean"
                },
                "lesson_id": {
                    "type": "string"
                },
                "lesson_title": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                }
            }
        },
        "__.LogInReq": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "__.LogInResp": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "__.MonthlyProgressResponse": {
            "type": "object",
            "properties": {
                "lessons_completed": {
                    "type": "integer"
                },
                "month": {
                    "type": "string"
                },
                "most_improved_skill": {
                    "type": "string"
                },
                "new_words_learned": {
                    "type": "integer"
                },
                "total_minutes_practiced": {
                    "type": "integer"
                },
                "total_xp_earned": {
                    "type": "integer"
                }
            }
        },
        "__.ParticipateLessonResp": {
            "type": "object",
            "properties": {
                "language": {
                    "$ref": "#/definitions/__.Languages"
                },
                "lesson": {
                    "$ref": "#/definitions/__.Lessons"
                },
                "theme": {
                    "type": "string"
                },
                "vocabulary": {
                    "$ref": "#/definitions/__.Vocabulary"
                }
            }
        },
        "__.ProgressByLanguageResponse": {
            "type": "object",
            "properties": {
                "grammar_rules_mastered": {
                    "type": "integer"
                },
                "language": {
                    "type": "string"
                },
                "lessons_completed": {
                    "type": "integer"
                },
                "level": {
                    "type": "string"
                },
                "listening_comprehension": {
                    "type": "integer"
                },
                "speaking_fluency": {
                    "type": "integer"
                },
                "vocabulary_learned": {
                    "type": "integer"
                },
                "xp": {
                    "type": "integer"
                }
            }
        },
        "__.RefreshTokenResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "__.RegisterReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "native_language": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "__.RegisterResp": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "__.ResetPasswordReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "__.Skill": {
            "type": "object",
            "properties": {
                "comprehension_rate": {
                    "type": "integer"
                },
                "fluency_rate": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "progress_to_next_level": {
                    "type": "integer"
                },
                "rules_mastered": {
                    "type": "integer"
                },
                "words_learned": {
                    "type": "integer"
                }
            }
        },
        "__.SkillsResponse": {
            "type": "object",
            "properties": {
                "language": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/__.Skill"
                    }
                }
            }
        },
        "__.StartExerciceResp": {
            "type": "object",
            "properties": {
                "exercise": {
                    "$ref": "#/definitions/__.Exercise"
                },
                "language": {
                    "$ref": "#/definitions/__.Languages"
                },
                "lesson": {
                    "$ref": "#/definitions/__.Lessons"
                }
            }
        },
        "__.StartLearningReq": {
            "type": "object",
            "properties": {
                "language": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "__.StartLearningResp": {
            "type": "object",
            "properties": {
                "lesson_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "next_lesson": {
                    "$ref": "#/definitions/__.Lessons"
                }
            }
        },
        "__.UpdateProfileReq": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "learning_languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "native_language": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "__.UpdateProfileResp": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "native_language": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "__.UpdateSettingsReq": {
            "type": "object",
            "properties": {
                "daily_goal": {
                    "type": "string"
                },
                "difficulty_level": {
                    "type": "string"
                },
                "notifications_enabled": {
                    "type": "boolean"
                },
                "preferred_learning_time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "__.Vocabulary": {
            "type": "object",
            "properties": {
                "example_lessons": {
                    "type": "string"
                },
                "translation": {
                    "type": "string"
                },
                "word": {
                    "type": "string"
                }
            }
        },
        "__.WeeklyProgressResponse": {
            "type": "object",
            "properties": {
                "lessons_completed": {
                    "type": "integer"
                },
                "most_active_day": {
                    "type": "string"
                },
                "new_words_learned": {
                    "type": "integer"
                },
                "total_minutes_practiced": {
                    "type": "integer"
                },
                "total_xp_earned": {
                    "type": "integer"
                },
                "week_end": {
                    "type": "string"
                },
                "week_start": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authourization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "",
	Description:      "Voting service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	// LeftDelim:        "{{",
	// RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
