version: '3.8'

services:
  progress:
    build: .
    ports:
      - "8085:8085"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=your_user
      - DB_PASSWORD=your_password
      - DB_NAME=your_database

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
